## Tic Tac Toe

This is a player v computer game of Tic Tac Toe implemented using Python

In [2]:
import numpy as np

In [91]:
ttt=np.ones((3,3))
ttt=(-1)*ttt
print ttt

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


In [103]:
ttt[0,:]=2
ttt==-1


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [65]:
print ttt
print ttt.shape
ttt[1,2]=1
ttt[0,]=[1,0,1]
ttt[2,2]=0
ttt[1,1]=1
ttt[2,0]=1
ttt[1,0]=1
print ttt

[[ 1.  0.  1.]
 [-1.  1.  1.]
 [ 1.  0.  0.]]
(3, 3)
[[ 1.  0.  1.]
 [ 1.  1.  1.]
 [ 1.  0.  0.]]


In [86]:
def win(ttt,num):
    zero_map=np.array([num,num,num])
    
    # diagonal
    if np.array_equal(np.diag(ttt),zero_map) or np.array_equal(np.diag(np.fliplr(ttt)),zero_map):
        print "Diagonal"
        return True
    
    for i in range(ttt.shape[0]):
        # row
        if np.array_equal(ttt[i,:],zero_map):
            print "Row"
            return True
        # col
        if np.array_equal(ttt[:,i],zero_map):
            print "Col"
            return True
        
    return False

win(ttt,2)

Diagonal


True

In [59]:
#print "Row:"
row=raw_input("Row:")

Row:4


In [60]:
col=raw_input("Col:")

Col:5


In [62]:
print int(row),int(col)

4 5


In [66]:
if -1 in ttt:
    print "yes"

In [79]:
print ttt
ttt[0,2]=2
ttt[1,2]=1
def prettyprint(ttt):
    res=np.chararray(ttt.shape)
    for i in range(ttt.shape[0]):
        for j in range(ttt.shape[1]):
            if ttt[i,j]==1:
                res[i,j]="o"
            elif ttt[i,j]==2:
                res[i,j]="x"
            elif ttt[i,j]==-1:
                res[i,j]=" "
    print res
prettyprint(ttt)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
[['' '' 'x']
 ['' '' 'o']
 ['' '' '']]


In [90]:
ttt=np.ones((3,3))
ttt=(-1)*ttt
print ttt
prettyprint(ttt)
while True:

    if win(ttt,1):
        print "Zero wins"
        break
    if win(ttt,2):
        print "Cross wins"
        break
    if -1 not in ttt:
        print "Draw"
        break
    while True:
        row,col=int(raw_input("Row:")),int(raw_input("Col:"))
        if ttt[row,col]==-1:
            break
        else:
            print "Give another values"
    ttt[row,col]=2
    while True:
        row_zero,col_zero=np.random.randint(0,3),np.random.randint(0,3)
        if ttt[row_zero,col_zero]==-1:
            break
    ttt[row_zero,col_zero]=1
    prettyprint(ttt)
    
prettyprint(ttt)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
[['' '' '']
 ['' '' '']
 ['' '' '']]
Row:0
Col:0
[['x' '' '']
 ['o' '' '']
 ['' '' '']]
Row:0
Col:2
[['x' '' 'x']
 ['o' '' '']
 ['o' '' '']]
Row:1
Col:1
[['x' '' 'x']
 ['o' 'x' '']
 ['o' '' 'o']]
Row:1
Col:2
[['x' '' 'x']
 ['o' 'x' 'x']
 ['o' 'o' 'o']]
Row
Zero wins
[['x' '' 'x']
 ['o' 'x' 'x']
 ['o' 'o' 'o']]


In [85]:
print ttt


[[ 2.  1.  2.]
 [ 1.  2.  2.]
 [ 1.  1.  2.]]
